// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awkdbihqtkvgrjvwpujd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3a2RiaWhxdGt2Z3JqdndwdWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDUyMjEsImV4cCI6MjA2NzM4MTIyMX0.-HjpPlay0pq-dH3YwIWN_WTfeAfbfmDMhGxNv-t9c5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});